### ISSUE TITLE
missing response body for referral_codes validate endpoint

### ISSUE THREAD

**Issue by wsmoak** [chargify/api-reference-export#1]
Text says the referral code will be returned, but there is no response body shown with the 200.  Where/how does it get returned?

![chargify-referral-codes-api-docs](https://cloud.githubusercontent.com/assets/20140/22697753/762ed0f8-ed20-11e6-8576-a589f91d4846.png)

**Comment by woodchopgirl** [comment]
Fixed! I don't have access to close the issue or assign it to myself, but it has been addressed here:

https://reference.chargify.com/v1/referral-codes/referrals-intro
